export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const FETCH_EXPENSES = 'FETCH_EXPENSES'; 
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
