export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const FETCH_EXPENSES = 'FETCH_EXPENSES'; 
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';

// Error types
export const FETCH_EXPENSES_ERROR = 'FETCH_EXPENSES_ERROR';
export const ADD_EXPENSE_ERROR = 'ADD_EXPENSE_ERROR';
export const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR';
export const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR';
